### PR TITLE
Unit tests spike

### PR DESCRIPTION
**Pull request by sean-gilliam**
This PR adds a very basic set of unit tests.

I chose to use [Catch2](https://github.com/catchorg/Catch2) since it has [CMake integration](https://github.com/catchorg/Catch2/blob/master/docs/cmake-integration.md).

Mainly used to show examples and get the ball rolling on integrating more detailed unit tests in the future.

> NOTE: 
> I moved the main() function from comm.c to main.c. I did this since I could exclude that function from the linker.

### CODE REVIEW

**Comment by rezalas** [comment]
With the second makefile, do we need to set up a new task in vscode configs to clean and build the tests along with the project?

**Comment by sean-gilliam** [comment]
Sure we can do that. Right now I've just been making them separately.

**Comment by rezalas** [comment]
The vscode settings shouldn't upload to the repo (despite that they are because I messed that up!) I was just wondering if you had done that on your side so I can add it to the instructions for setting up an environment if so.

**Comment by sean-gilliam** [comment]
@rezalas here is my current task.json file for the project. It builds both source and tests.

https://gist.github.com/sean-gilliam/e991bd0716a69a73165f350b855f61e6

**Pull request merged**
