### PR TITLE
testing ninja build system

### PR DESCRIPTION
**Pull request by sean-gilliam**

### CODE REVIEW

**Comment by sean-gilliam** [comment]
using ninja

build times
===
```
real	4m30.437s
user	5m11.026s
sys		0m32.260s
```

test times
===
```
real	0m0.155s
user	0m0.030s
sys		0m0.012s
```

**Comment by rezalas** [comment]
These times are looking good so far!

**Comment by sean-gilliam** [comment]
using make

build times
===
```
real	5m49.923s
user	3m1.561s
sys		0m20.780s
```

test times
===
```
real	0m0.133s
user	0m0.022s
sys		0m0.007s
```

**Comment by sean-gilliam** [comment]
Looks like using `ninja` instead of `make`, we can cut off approx 79s from the build time while building under Travis.

**Comment by rezalas** [comment]
Lets do it. What's the build package for ninja so I can add it to the README?

**Comment by sean-gilliam** [comment]
https://github.com/ninja-build/ninja/wiki/Pre-built-Ninja-packages

**Comment by sean-gilliam** [comment]
@rezalas Hold on this for a second.

**Comment by sean-gilliam** [comment]
@rezalas okay this PR is good to go. I know why #75 doesn't like ninja.

**Comment by sean-gilliam** [comment]
@rezalas Okay go for it. No need to hold this up while i dork with #75.

**Pull request merged**
